-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Creato il: Ott 27, 2022 alle 14:44
-- Versione del server: 10.4.24-MariaDB
-- Versione PHP: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `smart_cart`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `ricetta`
--

CREATE TABLE `ricetta` (
  `id_ricetta` int(11) NOT NULL,
  `descrizione` varchar(255) DEFAULT NULL,
  `immagine` varchar(255) DEFAULT NULL,
  `importo` double DEFAULT NULL,
  `nome` varchar(255) DEFAULT NULL,
  `procedimento` varchar(255) DEFAULT NULL,
  `tipo` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

--
-- Dump dei dati per la tabella `ricetta`
--

INSERT INTO `ricetta` (`id_ricetta`, `descrizione`, `immagine`, `importo`, `nome`, `procedimento`, `tipo`) VALUES
(1, 'La pasta alla siciliana è un primo piatto super gustoso, di quelli che portano l\'allegria in tavola! Nonostante il nome, la ricetta ha origini ', 'img/immagini_ricette/pasta-alla-siciliana.jpg', 10, 'Pasta alla siciliana', 'Per preparare la pasta alla siciliana lavate e spuntate le melanzane, tagliatele a bastoncini e friggetele in abbondante olio di arachidi. Una volta dorate prelevatele con una schiumarola e mettetele sulla carta assorbente.\nPreparate un sugo di pomodoro c', 'Primo piatto'),
(2, 'I paccheri alla napoletana sono un primo piatto di pasta gustoso e super saporito. Un sugo facile da preparare, con ingredienti semplici per questa ricetta che richiama alla convivialità di un pranzo della domenica.', 'img/immagini_ricette/paccheri-alla-napoletana.jpg', 5, 'Paccheri alla napoletana', 'Per preparare la pasta fredda alla Norma iniziate dai pomodori. Versate l\'olio in una padella ampia e unite l\'aglio. Fate soffriggere a fiamma molto bassa per un paio di minuti. A questo punto unite i pomodori, precedentemente tagliati a pezzetti, e lasci', 'Primo piatto'),
(3, 'Il risotto ai funghi porcini è un primo piatto prelibato dalla ricetta semplice. Cremoso ed avvolgente, molto delicato nella versione con i porcini freschi, è una pietanza autunnale perfetta in ogni occasione, dal pranzo alla cena. ', 'img/immagini_ricette/risotto-ai-funghi-porcini.jfif', 7, 'Risotto ai funghi porcini', 'Per realizzare il risotto ai funghi porcini dedicatevi per prima cosa alla pulizia dei funghi. Con un coltellino raschiate il gambo e tagliate accuratamente la parti più legnose. Con una spazzolina o un panno pulito eliminate tutti i residui di terra (ric', 'Primo piatto'),
(4, 'Le penne alla vecchia bettola sono una ricetta facile. Un primo piatto appetitoso dal condimento cremoso e avvolgente: una salsa delicata nel colore e nel sapore, leggermente alcolica per via della vodka. Un piatto di pasta che amerete proporre per una ce', 'img/immagini_ricette/penne-alla-vecchia-bettola.jfif', 6, 'Penne alla vecchia bettola', 'Per preparare le penne alla vecchia bettola, iniziate dal soffritto. Mondate la cipolla e l\'aglio e tritateli finemente. In una padella scaldate l\'olio, unite la cipolla, l\'aglio, il peperoncino intero e l\'origano secco e fateli soffriggere per qualche mi', 'Primo piatto'),
(5, 'Gli gnocchi al pomodoro gratinati sono un modo semplice e veloce di servire gli gnocchi di patate al forno. Un vero primo piatto coccola grazie alla cremosità dalla besciamella, che addolcisce il sugo di pomodoro, e alla crosticina dorata che li rende gol', 'img/immagini_ricette/gnocchi-al-pomodoro-gratinati.jfif', 10, 'Gnocchi al pomodoro gratinati', 'Per realizzare gli gnocchi al pomodoro gratinati potete optare per degli gnocchi di buona qualità acquistati già pronti oppure prepararli in casa seguendo la nostra ricetta. Portate a ebollizione abbondante acqua salata in una pentola capiente. Preriscald', 'Primo piatto'),
(6, 'Sfiziose, croccanti fuori e soffici dentro: le polpette di zucchine e patate sono una ricetta facile che conquista tutti.', 'img/immagini_ricette/polpette-di-zucchine-e-patate.jfif', 7, 'Polpette di zucchine e patate', 'Per realizzare le polpette di zucchine e patate mettete per prima cosa le patate a lessare in una pentola di acqua fredda, leggermente salata. Portate l\'acqua a ebollizione e fate cuocere le patate fino a quando saranno tenere. Scolatele e lasciatele inti', 'Secondo piatto'),
(7, 'Con i calamari ripieni al forno è facile portare in tavola una ricetta stuzzicante e ricca di gusto. Si tratta di un secondo piatto di pesce più semplice da realizzare di quanto sembri​ e il risultato è un piatto sano e leggero che si adatta perfettamente', 'img/immagini_ricette/calamari-ripieni.jfif', 20, 'Calamari ripieni al forno', 'Iniziate la preparazione dei calamari ripieni al forno cominciando a separare il capo dai tentacoli. Sbollentate questi ultimi per 10 minuti in acqua salata e acidulata con un po’ di succo di limone, sgocciolateli e tritateli insieme al prezzemolo, all’ag', 'Secondo piatto'),
(8, 'Una ricetta sfiziosa, facile e veloce. Gli spiedini di patate, scamorza e pancetta sono un secondo piatto, o un antipasto, gustoso e divertente che si porta in tavola in poco più di 30 minuti.', 'img/immagini_ricette/spiedini-di-patate-scamorza-pancetta.jfif', 5, 'Spiedini di patate, scamorza e pancetta ', 'Per preparare gli spiedini di patate, scamorza e pancetta iniziate lavando molto bene le patate e ponendole in una casseruola con acqua fredda e sale. Lessatele per circa 25 minuti o comunque fino a quando saranno diventate tenere pur restando ancora sode', 'Secondo piatto'),
(9, 'Il filetto al pepe verde è un grande classico della nostra cucina, un secondo piatto raffinato e gustoso che permette di esaltare un taglio di carne di per sé già pregiato. Pronto in mezz\'ora.', 'img/immagini_ricette/filetto-al-pepe-verde.jfif', 20, 'Filetto al pepe verde', 'Per preparare il filetto al pepe verde per prima cosa avvolgete i medaglioni di filetto con lo spago da cucina. Dopo averli legati, passateli nel pepe verde schiacciato facendolo aderire bene su entrambi i lati dei medaglioni.\nIn una padella fate scioglie', 'Secondo piatto'),
(10, 'Ecco una ricetta strepitosa per gustare del pollo fritto morbido, croccante e super saporito. Il segreto sta in una marinata profumata e una panatura ricca e gustosa.Un secondo piatto da servire con salsa allo yogurt, patatine fritte o un\'insalata di dolc', 'img/immagini_ricette/pollo-fritto.jpg', 6, 'Pollo fritto', 'Per preparare il pollo fritto dovete per prima cosa tagliare il pollo a pezzi. Eliminate la pelle, disossatelo e riducetelo in pezzi più piccoli che raccoglierete in una ciotola.\nConditelo con il succo di limone, il prezzemolo tritato, l\'aglio a fettine e', 'Secondo piatto'),
(11, 'Saporiti, croccanti, i cestini di prosciutto e formaggio sono una vera tentazione! Uno stampo da muffin e 10 minuti di preparazione per servire un antipasto insolito che porterà una nota originale al vostro aperitivo.\n', 'img/immagini_ricette/cestini-di-prosciutto-e-formaggio.jfif', 5, 'Cestini di prosciutto e formaggio', 'Rivestite uno stampo per muffin con le fette di prosciutto cotto come base per i cestini prosciutto e formaggio. Preparate la farcia lavorando la ricotta con l\'uovo e aggiungendo il formaggio a dadini, sale e pepe. \nFarcite i cestini con il ripieno e info', 'Antipasto'),
(12, 'Le polpette al sugo sono un classico \"piatto della nonna\" che mette d\'accordo tutti, grandi e piccoli. Un secondo piatto semplice e gustoso.\n', 'img/immagini_ricette/polpette-al-sugo.jpg', 5, 'Polpette al sugo', 'Per realizzare le polpette al sugo private le fette di pane della crosta, spezzettatele e fatele ammorbidire in una ciotola con il latte. Lasciatele riposare e poi schiacciatele con una forchetta. In caso ci fosse del latte in eccesso, strizzate la mollic', 'Secondo piatto'),
(13, 'La moussaka è un ghiotto e sostanzioso pasticcio a base di melanzane, carne e patate. Un piatto unico irresistibile, e vera specialità, tipico della cucina greca.\n', 'img/immagini_ricette/moussaka.jpg', 10, 'Moussaka', 'Per preparare la moussaka iniziate dal sugo di carne: tritate la cipolla e fatela soffriggere in olio. Unitevi la carne e fatela rosolare in maniera uniforme. Mantenendo la fiamma vivace bagnate con il vino, lasciatelo sfumare e aromatizzate con il cumino', 'Piatto unico '),
(14, '\nParmigiana di melanzane celebre ricetta regionale italiana nota anche come Melanzane alla parmigiana. Ecco la ricetta più tradizionale che c’è.', 'img/immagini_ricette/parmigiana-di-melenzane.jfif', 20, 'Parmigiana di melenzane', 'Per preparare la Parmigiana di melanzane per prima cosa lavate le melanzane, mondate e tagliatele a fette dello spessore di circa mezzo centimetro nel senso della lunghezza. Una volta tagliate disponete le fette a strati in un colapasta, cospargete di sal', 'Piatto unico '),
(15, 'Le frittelle di fiori di zucca sono un antipasto da preparare quando questi deliziosi fiori commestibili sono di stagione. Una ricetta super sfiziosa per realizzare bocconcini soffici che suscitano grande entusiasmo in ogni occasione, a pranzo come a cena', 'img/immagini_ricette/frittelle-di-fiori-di-zucca.jfif', 4, 'Frittelle di fiori di zucca', 'Per realizzare le frittelle con i fiori di zucca iniziate per prima cosa a mondare i fiori togliendo i pistilli e i gambi e tagliandoli in due metà. Sciacquateli con molta delicatezza e fateli asciugare su una gratella.\nMisurate gli ingredienti e preparat', 'Antipasto'),
(16, '\nUn evergreen dell\'estate! Le bruschette al pomodoro piacciono a tutti, sono facili da fare, saporite e gustose\n', 'img/immagini_ricette/bruschetta-pomodoro.jpg', 2, 'Bruschette al pomodoro', 'Per preparare delle deliziose bruschette tagliate delle fette di pane abbastanza spesse da un filoncino e disponetele sulla leccarda, infornate a 180°. Fatele abbrustolire, basteranno pochi minuti. In alternativa potete usare la griglia (l\'ideale), una pi', 'Antipasto'),
(17, 'Invitanti, divertenti, irresistibili! Le mozzarelline fritte sono un classico dell\'aperitivo che piace a tutti, facili e veloci da preparare e ancora di più da gustare', 'img/immagini_ricette/mozzarelline-fritte.jfif', 5, 'Mozzarelline fritte', 'Iniziate a preparare le mozzarelline fritte facendole sgocciolare in un colino. Infarinatele e dopo aver sbattuto le uova, passatevi velocemente le mozzarelline.\nInfine, impanatele con cura facendo in modo che il pane aderisca bene. A questo punto in un t', 'Antipasto'),
(18, 'Creare nuove versioni del classico tiramisù consente di provare ogni volta un dolce goloso e irresistibile. Il tiramisù al cocco e cioccolato è un importante dessert per concludere una cena in bellezza.', 'img/immagini_ricette/tiramisu-al-cocco-cioccolato.jfif', 10, 'Tiramisù al cocco e cioccolato', 'Per preparare il tiramisù al cocco e cioccolato spezzettate 150 g di cioccolato e fatelo sciogliere a bagnomaria. Unitevi il latte di cocco riscaldato e mescolate bene. Tenete da parte.\nSeparate i tuorli dagli albumi e montate i primi con metà dello zucch', 'Dolce'),
(19, 'Il gelato alla vaniglia è un classico intramontabile, amato da tutti e molto versatile perché si abbina facilmente ad altre preparazioni dolci, oltre a essere ottimo consumato da solo. \n', 'img/immagini_ricette/gelati-vaniglia.jpg', 7, 'Gelato alla vaniglia', 'Per preparare il gelato alla vaniglia, versate in un pentolino il latte, la panna, mezza bacca di vaniglia e le scorze di limone e di arancia. Scaldate fino a quando si formeranno delle bollicine ai bordi della pentola, non oltre. Mentre il latte arriva a', 'Dolce'),
(20, 'La classica ricetta della torta di mele, soffice e ricca di gusto​. \n', 'img/immagini_ricette/torta-di-mele.jfif', 10, 'Torta di mele', 'Iniziate la preparazione della torta di mele montando in una ciotola il burro insieme allo zucchero semolato fino a ottenere un composto spumoso.\nUnite le uova, uno alla volta, il latte e la scorza di limone. Mescolate bene dopo ogni aggiunta. \nAggiungete', 'Dolce'),
(21, 'La granita al limone è un super classico dell’estate, rinfrescante e buonissima è l’ideale per una pausa rigenerante, in ogni momento della giornata.', 'img/immagini_ricette/granita-al-limone.jfif', 2, 'Granita al limone', 'Per preparare la granita al limone per prima cosa ricavate dai limoni freschi il succo e grattugiate un cucchiaio di scorza. Dopodichè procedete nella preparazione dello sciroppo. \nIn un pentolino sciogliete lo zucchero in 500 g di acqua e un cucchiaio di', 'Dolce'),
(22, 'La torta Susanna è un dolce tipico di Parma con un guscio di pasta frolla ripieno di crema alla ricotta ricoperto da cioccolato. Una torta morbida e golosissima, ideale come dessert a fine pasto oppure a merenda.', 'img/immagini_ricette/torta-susanna.jfif', 8, 'Torta susanna ', 'Per realizzare la torta Susanna iniziate a preparare la pasta frolla secondo la ricetta base. Dopo aver fatto riposare il panetto per un\'ora in frigorifero, stendete la pasta in una sfoglia dello spessore di 5 mm e utilizzatela per rivestire uno stampo a ', 'Dolce'),
(23, 'Se avete voglia di una colazione golosissima pronta in pochi minuti, i french toast alla Nutella sono quello che fa per voi. Perfetti anche per un brunch, questi sandwich dolci vi regaleranno attimi di vera gioia... anche se vi consigliamo di prepararli s', 'img/immagini_ricette/french-toast-alla-nutella.jpg', 3, 'French toast alla nutella', 'Preparare i french toast alla Nutella è facile e veloce. In una ciotola profonda sbattete l’uovo con il latte, il sale e l’estratto di vaniglia fino a ottenere un composto omogeneo. Spalmate circa 1 cucchiaio di Nutella su ciascuna fetta di pan brioche.\nD', 'Dolce'),
(24, 'Ecco la buonissima ricetta delle Tagliatelle Alla Bolognese. Il ragù alla bolognese è un condimento dell\'Emilia Romagna con carne tritata che si prepara in vari modi, a seconda della carne che condiziona il tempo di cottura. Esistono molte versioni tra cu', 'img/immagini_ricette/tagliatelle-con-ragu-alla-bolognese.jfif', 10, 'Tagliatelle alla bolognese', 'Per la ricetta del ragù alla bolognese, scaldate in una casseruola 3-4 cucchiai di olio e una noce di burro, unite sedano, carota e cipolla tritati e fate appassire sulla fiamma moderata. Aggiungete la pancetta, a dadini, e, dopo 2-3 minuti, tutta la carn', 'Primo piatto'),
(25, 'Il cavolfiore in pastella non dovrebbe mai mancare tra gli antipasti dei golosi pranzi o cene invernali, soprattutto tra gli antipasti della Vigilia di Natale! Ideale da servire anche come contorno o secondo piatto, è una vera delizia! Il cavolfiore è una', 'img/immagini_ricette/cavolfiore-in-pastella.jpg', 6, 'Cavolfiore in pastella', 'Per la ricetta laziale dei cavolfiori in pastella, lavate e mondate il cavolfiore; dividetelo in cimette dello stesso calibro.\nSbollentatele in acqua salata per 3 minuti; scolatele e asciugatele.\nPreparate la pastella: in una ciotola amalgamate la farina ', 'Antipasto'),
(26, 'Burrosi gusci di frolla con crema ariosa in bella vista e amarene sciroppate a decorare, per un dolce goloso ma delicato\n', 'img/immagini_ricette/gusci-crema-amarena.jpg', 4, 'Gusci di frolla con crema e amarene', 'Scaldate il latte con la metà dello zucchero. A parte mescolate i tuorli con il resto dello zucchero e l’amido di mais.\nVersate il latte caldo sui torli, mescolate bene, poi riportate sul fuoco e cuocete fino a quando la crema non si sarà addensata. Togli', 'Dolce'),
(27, 'A tutti coloro che amano la zucca e desiderano utilizzarla in nuovi, sorprendenti piatti, ecco qui la più cremosa tra le pastasciutte\n', 'img/immagini_ricette/celentani-alla-zucca.jpg', 7, 'Celentani alla zucca', 'Per la ricetta dei celentani alla zucca, tagliate a pezzetti la zucca e lessatela nel latte per 15 minuti. Salate e frullate tutto.\nPer la ricetta dei celentani alla zucca, tagliate a pezzetti la zucca e lessatela nel latte per 15 minuti. Salate e frullat', 'Primo piatto'),
(28, 'La bistecca al forno con patate è una ricetta molto semplice da realizzare: una bistecca di manzo tenera come burro accompagnata da un contorno di patate al forno, con l\'eventuale aggiunta a piacere di altre verdure, in grado di soddisfare tutti i gusti, ', 'img/immagini_ricette/bistecca-marchigiana-con-patate-e-salsa-verde.jpg', 9, 'Bistecca marchigiana con patate e salsa verde', 'Per la ricetta della bistecca marchigiana con patate e salsa verde, preparate la carne per la frollatura: spalmatela con il burro salato in modo da ricoprirla in ogni punto e riponetela per 10 giorni in frigo al riparo da odori forti.\nAccendete una genero', 'Secondo piatto'),
(29, 'Abbiamo preso ispirazione dalla pizza di scarola e l\'abbiamo trasformata in rotolo, con qualche modifica e l\'aggiunta della salsiccia che ha sempre il suo perché', 'img/immagini_ricette/rotolo-mozzarella-salamella-scarola.jfif', 6, 'Rotolo con mozzarella, salamella e scarola', 'Per la ricetta del rotolo con mozzarella, salamella e scarola, mescolate nell’impastatrice 500 g di farina con il lievito sbriciolato, quindi aggiungete 250 g di acqua fredda, un po’ per volta, sempre impastando. Unite poi 5 g di zucchero, infine 10 g di ', 'Secondo piatto'),
(30, 'Torta salata o pizza, non riuscite a scegliere? Puntate sulla parigina, pasta lievitata e sfoglia insieme con un ripieno super gustoso', 'img/immagini_ricette/pizza-parigina.jpg', 8, 'Pizza parigina', 'Per la ricetta della pizza parigina con besciamella, peperoni e pomodorini sott\'olio, mescolate nell’impastatrice 500 g di farina con il lievito sbriciolato, quindi aggiungete 250 g di acqua fredda, un po’ per volta, sempre impastando. Unite quindi lo zuc', 'Piatto unico '),
(31, 'Yogurt magro e yogurt greco uniti in un mix leggero, fresco e salutare per una bevanda da gustare con tranquillità senza pensare a calorie o stress', 'img/immagini_ricette/frullato-cetriolo-yogurt-al-lime-e-curcuma.jfif', 4, 'Frullato di cetriolo e yogurt al lime e curcuma', 'Per la ricetta del frullato di cetriolo e yogurt al lime e curcuma, frullate insieme lo yogurt magro, 200 g di yogurt greco, il cetriolo pelato, lo zenzero a fettine, 1 cucchiaino di curcuma, il succo e la scorza grattugiata del lime.\nSuddividete in 2 bic', 'Bevanda'),
(32, 'Passato e futuro. Il punto d’incontro trovato nella cucina dello spiedo e della brace: niente di più primitivo e attuale', 'img/immagini_ricette/lattuga.webp', 8, 'Lattuga, mandorla amara e uova di trota alla brace', 'Mettete a bagno le mandorle e la mandorla armellina in 200 g di acqua per 2 giorni; infine frullatele con un po’ della loro acqua e un pizzico di sale fino a ottenere una consistenza liscia e omogenea.\nMondate le lattughe conservando le foglie esterne. Po', 'Contorno'),
(33, 'Un tempo questo piatto si preparava bagnando le fette di pane secco nell’acqua di mare, o in acqua salata (il nome viene da qui). Si rinforzava poi il «brodo» stracciandovi le uova fino a farle rapprendere', 'img/immagini_ricette/acquasale.jpg', 10, 'Acquasale', 'Per la ricetta tradizionale della Basilicata acquasale, tritate sedano e cipolla e rosolateli in una casseruola con un filo di olio, origano, peperoncino e un pizzico di sale per un paio di minuti.\nPer la ricetta tradizionale della Basilicata acquasale, t', 'Contorno'),
(34, 'Unisce una salsa vellutata ai funghi trifolati, i gallinacci, che sono comuni in Molise, tutto poi frullato in una crema. Un classico primo piatto d’autunno, reso nutriente e saporito dall’utilizzo del brodo di carne nella salsa vellutata', 'img/immagini_ricette/crema-di-gallinacci.jpg', 6, 'Crema di gallinarci', 'Per la ricetta molisana della crema di gallinacci, fondete il burro in una padella, aggiungete la farina, mescolando con attenzione per non formare grumi. Aggiungete il brodo caldo, sempre mescolando, e cuocete la salsa vellutata per circa 5 minuti.\nTrita', 'Primo piatto'),
(35, 'Tipico dell’Isola di San Pietro, nel Sud della Sardegna, famosa per la pesca dei tonni, mostra uno dei modi più semplici per cuocere questo pesce, in pezzi grossi semplicemente lessati. Anche l’abbinamento con la cipolla risponde al criterio della massima', 'img/immagini_ricette/tonno-con-cipolle.jpg', 13, 'Tonno con cipolle', 'Per la ricetta sarda del tonno con cipolle, mettete il tonno in una casseruola piena di acqua. Salate e portate a bollore, quindi cuocete per 30 minuti.\nSbucciate la cipolla e affettatela. Mettetela in una ciotola immersa in acqua calda, in modo che perda', 'Secondo piatto'),
(36, 'I fichi sono già squisiti al naturale, ma con l\'aggiunta di elementi croccanti o freschi diventano divini. Potete rinforzare l’aroma dei fichi sfumandoli con un po’ di di rum', 'img/immagini_ricette/fichi-in-padella-pain-perdu-e-gelato-al-rosmarino.jpg', 7, 'Fichi in padella, pain perdu e gelato al rosmarino', 'Per la ricetta dei fichi in padella, pain perdu e gelato al rosmarino, portate a ebollizione 500 g di latte con 120 g di zucchero e il rosmarino; lasciate intiepidire per 10 minuti, filtrate, aggiungete la panna e mescolate. Trasferite il composto nella g', 'Dolce');

--
-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `ricetta`
--
ALTER TABLE `ricetta`
  ADD PRIMARY KEY (`id_ricetta`);

--
-- AUTO_INCREMENT per le tabelle scaricate
--

--
-- AUTO_INCREMENT per la tabella `ricetta`
--
ALTER TABLE `ricetta`
  MODIFY `id_ricetta` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
